# Generated by Django 3.1.6 on 2022-07-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.CharField(blank=True, max_length=12, unique=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('studentstatus', models.CharField(blank=True, default='', max_length=50)),
                ('professor', models.CharField(blank=True, max_length=50)),
                ('school', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
